### PR TITLE
Add gulp auto translation

### PR DESCRIPTION
**Pull request by ldittmar81**
This pr add gulp auto translation and some missing translations.

For informations about gulp automatic translation (german): https://forum.iobroker.net/topic/19047/gulp-ist-kein-hexenwerk-auto-translation

### CODE REVIEW

**Comment by Apollon77** [comment]
Thank you!

**Comment by Apollon77** [comment]
what are thse nbproject files?

**Comment by ldittmar81** [comment]
> what are thse nbproject files?

Netbeans

**Comment by Apollon77** [comment]
Hey @ldittmar81 sorry, I was too fast with my local changes ... could you update your PR? Sorry for that

**Comment by Apollon77** [comment]
@ldittmar81 any time to rebase? ;-)

**Pull request closed without merging**
