### PR TITLE
device list additions

### PR DESCRIPTION
**Pull request by fbeister**
* add image for Echo Flex
* add entry for FireTV Stick Lite 2020
* add entry for Echo Dot 4.Gen

### CODE REVIEW

**Comment by fbeister** [comment]
The new images are not shown correctly - perhaps you want to fix that. For my devices, the *types* are correctly matched, though.

**Comment by Apollon77** [comment]
aahh there should be no leading slash ... I fix it

**Comment by Apollon77** [comment]
Please check github adapter version

**Comment by fbeister** [comment]
Works as expected

Bildschirmfoto von 2021-01-31 09-11-44

**Comment by Apollon77** [comment]
Cool, thx ... there were many invalid pathcs included :-) I will release soon

**Pull request merged**
