### PR TITLE
Added Echo Plus 2.Gen and Echo Sub to main.js and icons.

### PR DESCRIPTION
**Pull request by xfjx**

### CODE REVIEW

**Comment by Apollon77** [comment]
Please add the capabilities of the devices as comment as with most other lines. Thank you

**Comment by xfjx** [comment]
added capabilities for all devices that I own

**Comment by Apollon77** [comment]
Thank you!!

**Comment by LilaQ** [comment]
@Apollon77 Do you still need to push these changes to the ioBroker adapter? Still can't see the "commands" section with my Echo Plus 2nd gen :/

**Comment by Apollon77** [comment]
I do not have released a new version. You can update from GitHub to have your changes in.  Need to find some hours time to do some more changes and prepare a new release but I have an other topic inbred to finish first.

**Pull request merged**
