### PR TITLE
Fix for Issue #291 

### PR DESCRIPTION
**Pull request by dklinger**
Fix for Issue #291

### CODE REVIEW

**Comment by Apollon77** [comment]
The latest changes are strange ... what you plan? I decided to rather check logs more deeps to find the root cause of the problem instead that fix, but I needs a day more

**Comment by dklinger** [comment]
It's just a type/existence check on indexOf. If it exists and it is a method, it proceeds. Otherwise it returns null. This won't break any existing functionality but also leads not no error on any kind of other devices which also do not have this method in it's definition. Checking logs is also a good approach but nothing I can do as I don't have them ;)

**Comment by Apollon77** [comment]
My question above more referred to the "package.json" push you did ... 

On the fix: Yes in fact it is possible to fix it taht way ... but if that error apperas then the JSON received from Amazon is different then expected, so I would more adjust to it AND male it more safe for the future. I already got such a log, just need to find time (and need to fix something else in an other project before)

**Comment by dklinger** [comment]
WTF?!!! That wasn't by intention. I changed it in my branch and it was somehow auto-taken into the PR :D

Ok, sure. I understand. My approach was different as I wouldn't want one simple (new) device to break my entire ioBroker-Alexa-connection. I don't have a doorbell now for 2 weeks just because of one device which doesn't fit to the expected json.

**Comment by Apollon77** [comment]
I fixed the root cause (hopefully. Will come in next version ... you are welcome to try github version ... but is experimental at the moment!!

**Pull request closed without merging**
